name: ${artifactId}
version: ${version}
author: Doomworks
main: co.neweden.playtimer.PTMain
depend: [WebsiteLink]

commands:
  playtime:
    description: Shows the users total play time.
    permission: playtimer.use
    permission-message: You don't have permission to use this.
    depend: [Vault]
permissions:
  playtimer.*:
    description: Gives access to all PlayerTimer permission nodes
    default: op
    children:
      playtimer.use: true
  playtimer.use:
    description: Gives access to basic PTMain functions.
